### ISSUE TITLE
Redirect only to default lang

### ISSUE THREAD

**Issue by ghost** [plauclair/AutodetectLanguage#2]
Hi, i've installed this module on a dev site, with two language **en** ed **it**. On the configuration page i've setted the redirect to **it**, and only for home page, but the system redirect me only to en. Examining the source i've found you have inserted a function inside an if statement, at line 69.

The link to website is http://www.nobilevet.com/new-ws/

**Comment by plauclair** [comment]
Sorry for the delay. That function inside the if shouldn't cause a problem, I just didn't want to add useless functions to the global scope for no reason if the script doesn't need to run. 

Could you tell me how your languages are set up? All language names must be using valid language code. For example, if your default language is English, you need to insert "en" (or a specific locale) in the module settings, an "it" in your Italian language _name_. Is that the case?

Otherwise, what browser are you using, and could you please copy the output of `var_dump($_SERVER['HTTP_ACCEPT_LANGUAGE'])`. 

![capture d ecran 2015-05-07 a 22 36 13](https://cloud.githubusercontent.com/assets/171120/7529638/9ac36200-f509-11e4-8853-14c0c0efb519.png)

**Comment by ghost** [comment]
Hi plauclair, thank you to reply to my issue, e don't worry about delay in answer. I've setupped my languages indicating the full name language as name and as ISO code the title of language. Now i try to change them as you indicated in your screenshot, and consequently setup the home page name. I'll inform you on progress.

**Comment by plauclair** [comment]
Thanks Patrick, I have updated the documentation on my side. Cheers!
